### ISSUE TITLE
Additional methods for the Matrix 

### ISSUE THREAD

**Issue by aubertc** [seiller/pymwp#12]
I believe it could be beneficial to add to the [Matrix.py](https://github.com/seiller/pymwp/blob/master/pymwp/matrix.py) class:

- A "fixpoint" method, that computes the star operation (1 + M + M^2 + M^3 + …)
- An "equals" method that returns true if two matrices are identical.

**Comment by seiller** [comment]
The fixpoint method (and maybe the equal one) should have existed at some point. We can discuss the most efficient way to compute it; as sums are maximum, the sequence M, M^2, ... is increasing and one just needs to find a M^n that stabilises (M^n=M^n+M). But maybe computing M, M^2, M^4 (iterated products instead of summing with M each time) would be more efficient.

**Comment by aubertc** [comment]
Oh, and a "print" method.

**Comment by nkrusch** [comment]
> The fixpoint method (and maybe the equal one) should have existed at some point. 

we have [fixpoint](https://seiller.github.io/pymwp/relation/#pymwp.relation.Relation.fixpoint) method but it requires creating a `Relation` then matrix in that relation, then calling fixpoint.

The use case here is for computing fixpoint for a matrix (list of list) without needing Relation instance around it.

> maybe the equal one

We have polynomial equals. So for list of list of polynomials, need to do element-wise equals. It can be done but takes some time to write it. The use case is to look at some two matrices in isolation and be able to tell if they are equal.

> and a "print" method

yes, should add this.

**Comment by aubertc** [comment]
This is closed with https://github.com/seiller/pymwp/pull/15.
